version: 2

sources:
  - name: gz_raw_data
    description: greenweezeraw data sources

    tables:
      - name: raw_gz_sales
        description: sales of greenweez
      
      - name: raw_gz_ship
        description: ship of greenweez
        columns:
          - name: orders_id
            description: primary key of the column
            tests:
            - unique
            - not_null

      - name: raw_gz_product
        description: product of greenweez
        columns:
          - name: products_id
            description: primary key of the column
            tests:
            - unique
            - not_null
                


            
