version: 2

sources:
  - name: raw
    schema: gz_raw_data

    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenwez
      - name: ship
        identifier: raw_gz_ship
        description: ship of greenweez
      - name: product
        identifier: raw_gz_product
        description: product of greenweez
